version: '3'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=api
            - POSTGRES_PASSWORD=api
            - POSTGRES_DB=api
#        volumes:
#            - ./postgres:/var/lib/postgresql/data
        ports:
            - '5432:5432'
    events-pipeline:
        depends_on:
            - postgres
        image: 0xorg/event-pipeline@sha256:058e730018a8bdc31b1fdd68935eeb27bc728a0db579b41436c138cf73e830e1
        restart: always
        environment:
            ETHEREUM_RPC_URL: 'https://mainnet.infura.io/v3/cf3856d5c1aa45408c56a1029b45d712'
            CHAIN_ID: '1'
            POSTGRES_URI: 'postgres://api:api@postgres/api'
